In [26]:
import numpy as np

# Function to optimize
def objective_function(x):
    return - (x - 3)**2 + 9  # Peak at x = 3

In [33]:
# Bee Algorithm Parameters
num_bees = 5  # Total bees (scouts + workers)
num_iterations = 10  # Number of iterations
search_range = (-5, 10)  # Search space for x

In [34]:
# Step 1: Initialize Bees (random x values)
bees = np.random.uniform(search_range[0], search_range[1], num_bees)

In [35]:
bees

array([ 2.21837208,  8.32923479, -3.3062449 , -4.39132976,  9.45548318])

In [36]:
# Step 2: Evaluate nectar (function values)
nectar = np.array([objective_function(x) for x in bees])

In [37]:
nectar

array([  8.38905779, -19.40074348, -30.76872477, -45.63175565,
       -32.67326313])

In [38]:
# Step 3: Select the best bees
best_bee_idx = np.argmax(nectar)
best_bee = bees[best_bee_idx]

In [39]:
best_bee

np.float64(2.218372075634953)

In [40]:
# Step 4: Local Search (Exploitation)
new_local_solutions = np.random.uniform(best_bee - 0.5, best_bee + 0.5, num_bees - 1)

In [41]:
new_local_solutions

array([1.98524543, 2.12249387, 2.17846383, 2.25577816])

In [42]:
# Step 5: Global Search (Exploration)
new_scout_solutions = np.random.uniform(search_range[0], search_range[1], 1)

In [43]:
new_scout_solutions

array([-2.93508068])

In [44]:
# Combine local and global search
bees = np.concatenate(([best_bee], new_local_solutions, new_scout_solutions))

In [45]:
bees

array([ 2.21837208,  1.98524543,  2.12249387,  2.17846383,  2.25577816,
       -2.93508068])

In [46]:
for iteration in range(num_iterations):
    # Step 2: Evaluate nectar (function values)
    nectar = np.array([objective_function(x) for x in bees])
    
    # Step 3: Select the best bees
    best_bee_idx = np.argmax(nectar)
    best_bee = bees[best_bee_idx]
    
    # Step 4: Local Search (Exploitation)
    new_local_solutions = np.random.uniform(best_bee - 0.5, best_bee + 0.5, num_bees - 1)
    
    # Step 5: Global Search (Exploration)
    new_scout_solutions = np.random.uniform(search_range[0], search_range[1], 1)
    
    # Combine local and global search
    bees = np.concatenate(([best_bee], new_local_solutions, new_scout_solutions))

In [47]:
# Final best solution
best_x = best_bee
best_value = objective_function(best_x)

print(f"Best x found: {best_x:.4f}")
print(f"Maximum function value: {best_value:.4f}")

Best x found: 3.0008
Maximum function value: 9.0000


# Find the shortest path

In [48]:
import itertools
import numpy as np

# Define the distances between locations
distances = {
    ('A', 'B'): 2, ('A', 'C'): 5, ('A', 'D'): 7,
    ('B', 'C'): 3, ('B', 'D'): 6,
    ('C', 'D'): 4
}

In [49]:
distances

{('A', 'B'): 2,
 ('A', 'C'): 5,
 ('A', 'D'): 7,
 ('B', 'C'): 3,
 ('B', 'D'): 6,
 ('C', 'D'): 4}

In [51]:
# Generate all possible paths (permutations)
locations = ['A', 'B', 'C', 'D']
all_routes = list(itertools.permutations(locations))

In [52]:
# Function to calculate total distance of a given route
def route_distance(route):
    total_distance = 0
    for i in range(len(route) - 1):
        pair = tuple(sorted([route[i], route[i + 1]]))  # Ensure correct lookup
        total_distance += distances[pair]
    return total_distance

In [55]:
route_distance(locations)

9

In [56]:
route_distance(['B', 'C', 'A', 'D'])

15

In [57]:
# Bee Algorithm Parameters
num_bees = 5
num_iterations = 10

In [63]:
# Step 1: Initialize bees with random routes
bees = [list(np.random.permutation(locations)) for _ in range(num_bees)]

In [64]:
bees

[[np.str_('D'), np.str_('A'), np.str_('C'), np.str_('B')],
 [np.str_('B'), np.str_('A'), np.str_('C'), np.str_('D')],
 [np.str_('C'), np.str_('B'), np.str_('D'), np.str_('A')],
 [np.str_('B'), np.str_('D'), np.str_('C'), np.str_('A')],
 [np.str_('B'), np.str_('D'), np.str_('A'), np.str_('C')]]

In [65]:
# Step 2: Evaluate nectar (total route distance)
nectar = np.array([route_distance(route) for route in bees])

In [66]:
nectar

array([15, 11, 16, 15, 18])

In [67]:
# Step 3: Select the best bee (shortest route)
best_bee_idx = np.argmin(nectar)
best_bee = bees[best_bee_idx]

In [69]:
best_bee

[np.str_('B'), np.str_('A'), np.str_('C'), np.str_('D')]

In [79]:
# Step 4: Local Search (swap two cities in best route)
new_local_solutions = []
for _ in range(8):
    new_route = best_bee[:]
    i, j = np.random.choice(len(new_route), 2, replace=False)
    new_route[i], new_route[j] = new_route[j], new_route[i]
    new_local_solutions.append(new_route)

In [80]:
new_local_solutions

[[np.str_('A'), np.str_('B'), np.str_('C'), np.str_('D')],
 [np.str_('B'), np.str_('D'), np.str_('C'), np.str_('A')],
 [np.str_('B'), np.str_('A'), np.str_('D'), np.str_('C')],
 [np.str_('C'), np.str_('A'), np.str_('B'), np.str_('D')],
 [np.str_('A'), np.str_('B'), np.str_('C'), np.str_('D')],
 [np.str_('B'), np.str_('D'), np.str_('C'), np.str_('A')],
 [np.str_('C'), np.str_('A'), np.str_('B'), np.str_('D')],
 [np.str_('B'), np.str_('A'), np.str_('D'), np.str_('C')]]

In [77]:
# Step 5: Global Search (random new routes)
new_scout_solutions = [list(np.random.permutation(locations)) for _ in range(3)]

In [78]:
new_scout_solutions

[[np.str_('B'), np.str_('D'), np.str_('A'), np.str_('C')],
 [np.str_('A'), np.str_('D'), np.str_('C'), np.str_('B')],
 [np.str_('D'), np.str_('B'), np.str_('A'), np.str_('C')]]

In [81]:
# Combine local and global search
bees = [best_bee] + new_local_solutions + new_scout_solutions

In [82]:

for iteration in range(num_iterations):
    # Step 2: Evaluate nectar (total route distance)
    nectar = np.array([route_distance(route) for route in bees])
    
    # Step 3: Select the best bee (shortest route)
    best_bee_idx = np.argmin(nectar)
    best_bee = bees[best_bee_idx]
    
    # Step 4: Local Search (swap two cities in best route)
    new_local_solutions = []
    for _ in range(num_bees - 1):
        new_route = best_bee[:]
        i, j = np.random.choice(len(new_route), 2, replace=False)
        new_route[i], new_route[j] = new_route[j], new_route[i]
        new_local_solutions.append(new_route)

    # Step 5: Global Search (random new routes)
    new_scout_solutions = [list(np.random.permutation(locations)) for _ in range(1)]
    
    # Combine local and global search
    bees = [best_bee] + new_local_solutions + new_scout_solutions

In [83]:
# Final best solution
best_route = best_bee
best_distance = route_distance(best_route)

print(f"Best route found: {best_route}")
print(f"Shortest distance: {best_distance}")

Best route found: [np.str_('A'), np.str_('B'), np.str_('C'), np.str_('D')]
Shortest distance: 9


# location alocation

10 house
2 schole

## Initailze the bees